config/routes.rb
Rails.application.routes.draw do
  #root 'pages#home'
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  resources :cars
  #get 'home/index'
  get 'home/about'

  #root 'home#index'
  root 'cars#index'
  get 'home/inventory'
  get 'home/trucks'
  get 'home/sedans'
  get 'home/vans'
  get 'home/suv'
  get 'home/coupes'
  get 'home/sportcars'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
	belongs_to :user

	has_one_attached :image
	
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:regular, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	layout :set_layout 

	private

	def set_layout
		#if current_user && current_user.admin == true
		#Ensures you wont't error if not logged in when you check if admin
		if current_user&.admin?
			#if current_user && current_user.admin?
			"admin"
		else
			"application"
		end
	end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /cars or /cars.json
  def index
    @cars = Car.all 
  end


  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    #@car = Car.new
    @car = current_user.cars.build
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    #@car = Car.new(car_params)
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car.destroy!

    respond_to do |format|
      format.html { redirect_to cars_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @car = current_user.cars.find_by(id: params[:id])
    redirect_to cars_path, notice: "Not Authorized To Edit The Cars" if @car.nil?
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def car_params
      params.require(:car).permit(:car_brand, :car_model, :class_type, :year, :vin, :mileage, :color, :user_id, :price, :day3, :day5, :day7, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
    def about 

      def inventory

        def trucks

          def sedans

            def vans

              def suv

                def coupes

                  def sportcars

                  end
                end
              end
            end
          end
        end
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Car brand:</strong>
    <%= car.car_brand %>
  </p>

  <p>
    <strong>Class Model:</strong>
    <%= car.class_modle %>
  </p>

  <p>
    <strong>Class Type:</strong>
    <%= car.class_type %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= car.year %>
  </p>

  <p>
    <strong>Vin:</strong>
    <%= car.vin %>
  </p>

  <p>
    <strong>Mileage:</strong>
    <%= car.mileage %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= car.color %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= car.cost %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= car.day3 %>
  </p>

  <p>
    <strong>Cost:</strong>
    <%= car.day5 %>
  </p>

</div>

app/views/cars/_form.html.erb
<%= form_with(model: car) do |form| %>
  <% if car.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field ">
    <%= form.file_field :image %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :car_brand, style: "display: block" %>
    <%= form.text_field :car_brand, class:"form-control", placeholder:"Car Brand Name" %>
  </div>


  <br/>

  <div class="field form-group">
    <% form.label :car_model, style: "display: block" %>
    <%= form.text_field :car_model, class:"form-control", placeholder:"Car Model Name" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :class_type, style: "display: block" %>
    <%= form.text_field :class_type, class:"form-control", placeholder:"Class Type" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :year, style: "display: block" %>
    <%= form.text_field :year, class:"form-control", placeholder:"Year Model" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :vin, style: "display: block" %>
    <%= form.text_field :vin, class:"form-control", placeholder:"Vin Number " %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :mileage, style: "display: block" %>
    <%= form.text_field :mileage, class:"form-control", placeholder:"Mileage" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :color, style: "display: block" %>
    <%= form.text_field :color, class:"form-control", placeholder:"Color" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form-control", placeholder:"1 Day" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :day3, style: "display: block" %>
    <%= form.text_field :day3, class:"form-control", placeholder:"3 Days" %>
  </div>

  <br/>

  <div class="field form-group">
    <% form.label :day5, style: "display: block" %>
    <%= form.text_field :day5, class:"form-control", placeholder:"5 Days" %>
  </div>


  <br/>

  <div class="field form-group">
    <% form.label :day7, style: "display: block" %>
    <%= form.text_field :day7, class:"form-control", placeholder:"7 Days" %>
  </div>

  <div class="field form-group">
    <% form.label :user_id, id: :car_user_id, style: "display: block" %>
    <%= form.number_field :user_id, class:"form-control", value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car, class:"btn btn-secondary" %> 
  <br><br>
  <%= button_to 'Delete', @car, method: :delete, data: { turbo_confrim: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
  <br>
  <%= link_to "Back to cars", cars_path, class:"btn btn-dark" %>
</div>

app/views/cars/index.html.erb
<% if user_signed_in? %>

  <% if current_user.admin? %>
    <!-- Admin Dashboard -->
    <h1>Admin Dashboard</h1>
    <table class="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Car Brand And Model</th>
          <th>Class Type</th>
          <th>Year</th>
          <th>Vin</th>
          <th>Mileage</th>
          <th>Color</th>
          <th>1Day</th>
          <th>3Days</th>
          <th>5Days</th>
          <th>7Days</th>
          <!-- <th>User Id</th> -->
          <th> </th>
        </tr>
      </thead>
      <tbody>
        <% @cars.each do |car| %>
          <tr>
            <td>
              <%= link_to "#{car.car_brand} #{car.car_model}", car if car.car_brand.present? && car.car_model.present? %>
            </td>
            <td><%= car.class_type %></td>
            <td><%= car.year %></td>
            <td><%= car.vin %></td>
            <td><%= car.mileage %></td>
            <td><%= car.color %></td>
            <td><%= car.price %></td>
            <td><%= car.day3 %></td>
            <td><%= car.day5 %></td>
            <td><%= car.day7 %></td>
            <!-- <td><%= car.user_id %></td> -->
            <!-- <td><%= link_to "Show", car, class: "btn btn-secondary" %></td> -->
            <!-- <td><%= link_to "Edit", edit_car_path(car), class: "btn btn-secondary" %></td> -->
            <td><%= button_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <!-- Link to add a new car -->
    <%= link_to "New car", new_car_path, class: "btn btn-secondary" %>

  <% else %>

    <!-- Regular User View - Cars List -->
    <h1>Cars List</h1>

    <table class="table table-striped table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Car Brand And Model</th>
          <th>Class Type</th>
          <th>Year</th>
          <th>Vin</th>
          <th>Mileage</th>
          <th>Color</th>
          <th>1Day</th>
          <th>3Days</th>
          <th>5Days</th>
          <th>7Days</th>
          <!-- <th>User Id</th> -->
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cars.each do |car| %>
          <tr>
            <td>
              <%= link_to "#{car.car_brand} #{car.car_model}", car if car.car_brand.present? && car.car_model.present? %>
            </td>
            <td><%= car.class_type %></td>
            <td><%= car.year %></td>
            <td><%= car.vin %></td>
            <td><%= car.mileage %></td>
            <td><%= car.color %></td>
            <td><%= car.price %></td>
            <td><%= car.day3 %></td>
            <td><%= car.day5 %></td>
            <td><%= car.day7 %></td>
            <!-- <td><%= car.user_id %></td> -->
            <!-- <td><%= link_to "Show", car, class: "btn btn-secondary" %></td> -->
            <!-- <td><%= link_to "Edit", edit_car_path(car), class: "btn btn-secondary" %></td> -->
            
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

  
  <% end %>

  <!-- Common content for both admin and regular users -->
  <br><br/>

  <%= current_user.role %>
  <%= link_to "logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete} %>

<% else %>

  <!-- Non-signed-in users view -->
  <h1>Cars List</h1>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Car Brand And Model</th>
        <th>Class Type</th>
        <th>Year</th>
        <th>Vin</th>
        <th>Mileage</th>
        <th>Color</th>
        <th>1Day</th>
        <th>3Days</th>
        <th>5Days</th>
        <th>7Days</th>
        <!-- <th>User Id</th> -->
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @cars.each do |car| %>
        <tr>
          <td>
            <%= link_to "#{car.car_brand} #{car.car_model}", car if car.car_brand.present? && car.car_model.present? %>
          </td>
          <td><%= car.class_type %></td>
          <td><%= car.year %></td>
          <td><%= car.vin %></td>
          <td><%= car.mileage %></td>
          <td><%= car.color %></td>
          <td><%= car.price %></td>
          <td><%= car.day3 %></td>
          <td><%= car.day5 %></td>
          <td><%= car.day7 %></td>
          <!-- <td><%= car.user_id %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if current_user %>
    <%= current_user.role %>
    <%= link_to "logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete} %>
  <% else %>
    <p>You are not Admin! <%= link_to "Login", new_user_session_path %> to make changes.</p>
  <% end %>

<% end %>

app/views/cars/new.html.erb
<h1>Add New car</h1>
<br>
<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Back to cars", cars_path, class:"btn btn-dark" %>
</div>

app/views/cars/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"> 
    <%= @car.car_brand %> 
    <%= @car.car_model %>   
  </h1>
  <p class="lead">
    Car Model: <%= @car.class_type %>
    <br>
    Car Year: <%= @car.year %>
    <br>
    Vin Number: <%= @car.vin %>
    <br>
    Mileage: <%= @car.mileage %>
    <br>
    Color: <%= @car.color %>
    <br>
    1 Day Cost: <%= @car.price %>
    <br>
    3 Days Cost: <%= @car.day3 %>
    <br>
    5 Days Cost: <%= @car.day5 %>
    <br>
    7 Days Cost: <%= @car.day7 %>
    <br>
    <% if @car.image.attached? %>
      <p><%= image_tag(@car.image, style: "") %></p>
    <% end %>
  </p>
  <hr class="my-4">
  
  <%= link_to 'Edit', edit_car_path(@car), class: "btn btn-secondary" %>
  <%= link_to 'Back', cars_path, class: "btn btn-secondary" %>
  <br><br/>
  
  <%= button_to "Destroy this car", @car, method: :delete %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid"> 
    <%= link_to 'Car Rental App', root_path, class:"navbar-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

        <%# <<li class="nav-item">

            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li> %>


          <li class="nav-item">
            <%= link_to "About Us", home_about_path, class:"nav-link"%>
         
          </li>

          <%# <li class="nav-item">
            <%= link_to "Cars", cars_path, class:"nav-link"%>
    

          <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
            <%= link_to "Add Car", new_car_path, class:"nav-link"%>
         
            </li>

            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
           
            </li>

            <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
           
            </li>

            <% else %>
          <%#   <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
           
          
            <%# <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class:"nav-link"%> 
           
            <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
           
            </li>

            <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
           
            </li>

          <% end %>

          <% end %>
          
          
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu">
             <%= link_to 'Inventory', home_inventory_path,class:"dropdown-item"%>
             <%= link_to 'Trucks', home_trucks_path, class:"dropdown-item"%>
             <%= link_to 'Sedans', home_sedans_path, class:"dropdown-item"%>
             <%= link_to 'Suv', home_suv_path, class:"dropdown-item"%>
             <%= link_to 'Coupes', home_coupes_path, class:"dropdown-item"%>
             <%= link_to 'Sports Cars',home_sportcars_path, class:"dropdown-item"%>


            <a class="dropdown-item" href="#">Another action</a>

            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>


        <%# <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li> %>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

<p>
<h2>The Billy's Rental Company has been in business for over 10 years.</h2> 
<br><br/>
<h2>Need some wheels? We got you covered.</h2> 
<br><br/>
<h3>Contact us at: 1-708-111-1111
<br>
Email: Billy@gmail.com
<br>
Located in the USA</h3>
 </p>
<br><br/>
 <%= link_to 'Car Rental App', root_path, class:"btn btn-dark" %>

app/views/home/coupes.html.erb
<h2>Home#Coupes</h2>
Coupes in stock!!!!!!!!!!!!

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
This is my first Rails Webpage...

app/views/home/inventory.html.erb
<h1>Home#inventory</h1>
This is what we have to in our warehouse....

app/views/home/sedans.html.erb
<h1>Home#sedans</h1>
This is the sedans that we have in stock....

app/views/home/sportcars.html.erb
<h3>Home#Sport Cars</h3>
Sport Cars in stock!!!!!!!!!!!!

<br><br/>
<%= image_tag("2024-ford.jpg", size: "200x200", :alt => "rss feed") %>
2024 Ford F250

<br><br/>
<img src="..." class="rounded float-end" alt="...">

<br><br/>
<img src="..." class="img-fluid" alt="...">

<br><br/>
<picture>
  <source srcset="..." type="image/svg+xml">
  <img src="..." class="img-fluid img-thumbnail" alt="...">
</picture>

app/views/home/suv.html.erb
<h6>Home#suv</h6>
SUV's that are in stock.......

app/views/home/trucks.html.erb
<h1>Home#trucks</h1>

app/views/home/vans.html.erb
<h3>Home#vans</h3>
This is what we have to in our warehouse....

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
  <head>
  	<title>Adminable</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
      
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <br>
      Adminable
      <br/>
    <%= yield %>
  </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
	<%= current_user.role %>
	<%= link_to "logout", destroy_user_session_path, method: :delete, data: { turbo_method: :delete} %>
<% else %>
	<%= link_to "Login", new_user_session_path %>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>